name: 'GAWG Release action'
description: 'This action generates a tag and release for the project inside GitHub.'
author: Álvaro García Pizarro
branding:
  icon: 'git-commit'
  color: 'gray-dark'

inputs:
  config-json:
    type: string
    description: 'JSON string containing workflow config parameters.'
    required: true
  github-token:
    type: string
    description: 'GitHub token for authentication.'
    required: true

runs:
  using: "composite"
  steps:
    - name: 
      if: ${{ fromJson(inputs.config-json).RELEASE == 'disabled' }}
      shell: bash
      run: |
        echo "⚠️ Release is disabled. To enable it, set the RELEASE parameter to 'enabled' in the workflow configuration file."
        echo "⚠️ Release is disabled. To enable it, set the RELEASE parameter to 'enabled' in the workflow configuration file." >> $GITHUB_STEP_SUMMARY
        echo ""

    - name: Set up Git
      if: ${{ fromJson(inputs.config-json).RELEASE == 'enabled' }}
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Generate Workflow Summary Report
      if: ${{ fromJson(inputs.config-json).RELEASE == 'enabled' }}
      shell: bash
      run: |
        echo ""
        echo "This release has been automatically generated by the gawg workflow triggered on ${{ github.event_name }} by ${{ github.actor }} on ${{ github.repository }} repository (${{ github.ref }} branch)." >> summary.txt
        echo "🕒 Generated on: $(date)" >> summary.txt
        echo "🔗 Run URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> summary.txt
        echo "Automatic changelog and release notes are a PRO feature of the gawg workflow. Please contact us to include an automatic summary of changes." >> summary.txt

    - name: Generate TAG
      if: ${{ fromJson(inputs.config-json).RELEASE == 'enabled' }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash
      run: |
        PROJECT_VERSION=$(echo '${{ fromJson(inputs.config-json).PROJECT_VERSION }}')
        TAG_NAME="v${PROJECT_VERSION}"
        git tag $TAG_NAME
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} $TAG_NAME
    
    - name: Generate Release
      if: ${{ fromJson(inputs.config-json).RELEASE == 'enabled' }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash
      run: |
        PROJECT_VERSION=$(echo '${{ fromJson(inputs.config-json).PROJECT_VERSION }}')
        TAG_NAME="v${PROJECT_VERSION}"
        echo "Generating release"
        echo "Config JSON: ${{ inputs.config-json }}"
        RELEASE_NOTES=$(cat summary.txt)
        gh release create $TAG_NAME --title "$TAG_NAME" --notes "$RELEASE_NOTES" --repo ${{ github.repository }}
        echo "Release generated"