name: 'GAWG Release action'
description: 'This action generates a tag and release for the project inside GitHub.'
author: Álvaro García Pizarro
branding:
  icon: 'git-commit'
  color: 'gray-dark'

inputs:
  config-json:
    type: string
    description: 'JSON string containing workflow config parameters.'
    required: true

runs:
  using: "composite"
  steps:
    - name: 
      if: ${{ fromJson(inputs.config-json).RELEASE == 'disabled' }}
      shell: bash
      run: |
        echo "⚠️ Release is disabled. To enable it, set the RELEASE parameter to 'enabled' in the workflow configuration file."
        echo "⚠️ Release is disabled. To enable it, set the RELEASE parameter to 'enabled' in the workflow configuration file." >> $GITHUB_STEP_SUMMARY
        echo ""

    - name: Generate TAG
      if: ${{ fromJson(inputs.config-json).RELEASE == 'enabled' }}
      shell: bash
      run: |
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: generate release
      if: ${{ fromJson(inputs.config-json).RELEASE == 'enabled' }}
      shell: bash
      run: |
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
        echo "Generating release"
        echo "Config JSON: ${{ inputs.config-json }}"
        gh release create $TAG_NAME --title "Release $TAG_NAME" --notes "Release generated from workflow"
        echo "Release generated"
        